name: Generate Snake Animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run on every push to main/master branch
  push:
    branches:
      - main
      - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Generate the snake animation
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Xavi-003
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=A855F7&color_dots=#161b22,#4c1d95,#6d28d9,#8b5cf6,#a78bfa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push the animation to the "output" branch
      - name: Push github-contribution-grid-snake.svg to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true